config/routes.rb
Lstand::Application.routes.draw do
  get "welcome/index"
  
  
  match '/education',    to: 'welcome#education'
  match '/experience',   to: 'welcome#experience'
  match '/pers_in', to: 'welcome#pers_in'
  match '/prof_in', to: 'welcome#prof_in'
  match '/contact', to: 'welcome#contact'

root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def experience
  end
  
  def pers_in
  end

  def prof_in
  end
  
  def education
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hey - it's that guy, Isaac!</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Welcome", root_path %></li>
              <li><%= link_to "Education", education_path %></li>
              <li><%= link_to "Experience", experience_path %></li>
              <li><%= link_to "Professional Interests", prof_in_path %></li>
              <li><%= link_to "Personal Interests", pers_in_path %></li>
              <li class="active"><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

        <div class="container">
          <div class="row-fluid">
            <div class="span12">
            <h2>Here are six ways to start a conversation!</h2>
              <div class="span3">
                <a class="thumbnail" href="mailto:ielias@csumb.edu">
                  <img src="/assets/emailbadge.png" alt="email ielias@csumb.edu">
                    <h5 style="text-align:center" >Send an email</h5>
                </a>
              </div>
              <div class="span3">
                <a class="thumbnail" href="http://facebook.com/ielias.ca/">
                  <img src="/assets/fbbadge.png" alt="Reach me on Facebook">
                    <h5 style="text-align:center" >Reach me on Facebook</h5>
                </a>
              </div>
              <div class="span3">
                <a class="thumbnail" href="http://twitter.com/brainscraps/">
                  <img src="/assets/twitterbadge.png" alt="Reach me on Twitter">
                    <h5 style="text-align:center" >Tweet at me</h5>
                </a>
              </div>
              
            </div>
            <div class="row-fluid">
            <div class="span12">
            
              <div class="span3">
                <a class="thumbnail" href="http://plus.google.com/112809701138110263879/">
                  <img src="/assets/gplusbadge.png" alt="Google Plus">
                    <h5 style="text-align:center" >Circle me: Google+</h5>
                </a>
              </div>
              <div class="span3">
                <a class="thumbnail" href="http://pinterest.com/brainscraps/">
                  <img src="/assets/pinterestbadge.png" alt="Pinterest contact">
                    <h5 style="text-align:center" >Pinterest-ing...</h5>
                </a>
              </div>
              <div class="span3">
                <a class="thumbnail" href="http://www.linkedin.com/in/isaacelias">
                  <img src="/assets/linkedinbadge.png" alt="Reach me on Linked in">
                    <h5 style="text-align:center" >Connect: LinkedIn</h5>
                </a>
              </div>
              
            </div>
            
            
            
          
          </div>
       

      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012</p>
      </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/education.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Welcome", root_path %></li>
              <li class="active"><%= link_to "Education", education_path %></li>
              <li><%= link_to "Experience", experience_path %></li>
              <li><%= link_to "Professional Interests", prof_in_path %></li>
              <li><%= link_to "Personal Interests", pers_in_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

        <div class="container">
        	

       <h1>Education Information<h1> <br/>
        </div>
        <div class="row">
          <div class="span1" style="text-align: right;" >
            <h5>Bachelor of Science</h5> 
            
          </div>
          <div class="span8 well">
            <a class="thumbnail span2" href="<%= csumb_url %>" alt="CSUMB Logo"> <img src="assets/otter.png"></a>
            <div class="span5"> 
            	<ul><li>Gradution: May 2012 </li>
            		<li>Major: <%= link_to "Business Administration", bus_url %></li>
            		<li>Concentration: Marketing</li>
            		<li>Favorite Class: <a href=" <%= bus460_url %>" alt="Emerging Business Models">Ecommerce: Emerging Business Models</a></li>
            		<ul><li>Instructor: <%= link_to "Dr. Babita Gupta", babita_url %></li><li>Textbook: <%= link_to "Managing the Digital Enterprise - Michael Rappa", "http://www.digitalenterprise.org/index.html"%></li> </ul>
        		</ul>
    		</div>
          </div>
        </div>
        <div class="row">
          <div class="span1" style="text-align: right;" >
            <h5>Work Study</h5>
          </div>
          <div class="span8 well">
            <div class="thumbnail span2"><img src="assets/OperationIraqiFreedom.png" alt="OIF logo"></div>
            <div class="span5">
            	<ul>
            		<li>U.S. Army Intelligence 2004 - 2009</li>
            		<li>Deployed to Iraq (15 months) & Afghanistan (3 months)</li>
            		<li>Achievement & Commendation Medals for superior performance</li>
            		<li>Learned leadership in life-threatening situations</li>
            		<li>Survival/fitness skills</li>
            			
            	</ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span1" style="text-align: right;" >
            <h5>Associate of Arts</h5> 
            
          </div>
          <div class="span8 well">
            <div class="thumbnail span2"><img src="assets/dli_flags.jpg" alt="D L I F L C "></div>
            <div class="span5">
            	<ul>
            		<li>Middle Eastern Studies</li>
            		<li>16 months of full-time study</li>
            		<li>A.U.S.A. Award for Scholarship</li>
            		<li>Defense Language Aptitude, Modern Standard Arabic: 3 (speaking) / 3 (reading)</li>
            		<li>General education classes completed during "evenings/weekends"spare time</li>
            			
            	</ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span1" style="text-align: right;" >
            <h5>High School</h5> 
            
          </div>
          <div class="span8 well">
            <div class="thumbnail span2"><img src="assets/EdisonVikings.png" alt="Edison High School logo"></div>
            <div class="span5">
            	<ul>
            		<li>Edison High School - Stockton, California</li>
            		<li>Graduated as member of National Honors Society</li>
            		<li>Member of speech & debate team</li>
            		<li>Played in pep band and orchestra</li>
            		<li>Earned Eagle Scout award from the Boy Scouts of America</li>
            		<li>School mascot during basketball season</li>
            			
            	</ul>
            </div>
          </div>
        </div>

      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012</p>
      </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/experience.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Welcome", root_path %></li>
              <li><%= link_to "Education", education_path %></li>
              <li class="active"><%= link_to "Experience", experience_path %></li>
              <li><%= link_to "Professional Interests", prof_in_path %></li>
              <li><%= link_to "Personal Interests", pers_in_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

      <div class="container">
        <h2> My work experience is presented below &mdash;</h2> 
        <div class="span10 offset1">
        <h2> as a series of haikus. </h2>
        </div>
        <div class="row">
          <div class="span3 well" style="text-align: right;" >
            <h5>Door-to-door Sales</h5> 
            <h5><em>Stockton, California</em></h5>
          </div>
          <div class="span6 well">
            <h2>Behind every gate<br/>
              A story waits to be told<br/>
              Empathy enters</h2>
          </div>
        </div>
        <div class="row">
          <div class="span3 well" style="text-align: right;" >
            <h5>Furniture Delivery</h5> 
            <h5><em>Modesto, California</em></h5>
          </div>
          <div class="span6 well">
            <h2>When the road beckons<br/>
              Ride the bumps, take no scratches<br/>
              "Refreshed home, madame."</h2>
          </div>
        </div>
        <div class="row">
          <div class="span3 well" style="text-align: right;" >
            <h5>Hotel Reservation Sales</h5> 
            <h5><em>Stockton, California</em></h5>
          </div>
          <div class="span6 well">
            <h2>Away from your home<br/>
              Balance comfort, style, and price <br/>
              We'll find the sweet spot</h2>
          </div>
        </div>
        <div class="row">
          <div class="span3 well" style="text-align: right;" >
            <h5>Translation/Intelligence</h5> 
            <h5><em>U.S. Army</em></h5>
          </div>
          <div class="span6 well">
            <h2>Complete the mission<br/>
              Disregard opposition <br/>
              Keep pushing, brothers</h2>
          </div>
        </div>
        <div class="row">
          <div class="span3 well" style="text-align: right;" >
            <h5>Casual Dining Server</h5> 
            <h5><em>Seaside, California</em></h5>
          </div>
          <div class="span6 well">
            <h2>Resolving conflicts<br/>
              Smiling, doing nine things at once <br/>
              Pampered guests will return</h2>
          </div>
        </div>

      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012</p>
      </footer>

      </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Welcome", root_path %></li>
              <li><%= link_to "Education", education_path %></li>
              <li><%= link_to "Experience", experience_path %></li>
              <li><%= link_to "Professional Interests", prof_in_path %></li>
              <li><%= link_to "Personal Interests", pers_in_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

        <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <div class="row">
          <div class="span4">
            <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                  <img src="https://lh4.googleusercontent.com/-KPtKgpb8kms/TXRMx09QLzI/AAAAAAAACno/pXNYyIaCFOo/s400/06172009337.jpg" alt="">
                 <!-- <h5></h5> -->
                  
                </div>
              </li>
            </ul>
          </div>
          <div class="span6">
            <h1>Who's this?!</h1>
            <p>For some reason&mdash;unbeknownst to yours truly&mdash;you have chosen to seek out some information about one <strong>"Isaac Elias"</strong>. I hope you found the right one; if not, I know of a good <%= link_to "search engine", "http://www.google.com/search?q=%22Isaac+Elias%22" %>. </p>
            <p>Feel free to use the buttons across the top of this page to get to know more about me. One of the first things you should know is that I'm a people person, and acccordingly, I'd be thrilled to make your acquaintence! So use the yellow button if you'd like to - 
            <a href="<%= contact_path %>" class="btn btn-warning btn-large">Get in touch &raquo;</a></p>
          </div>
        </div>
        </div>

      <!-- Example row of columns -->
      <div class="row"> <p style="text-align:justify"><h1>So, tell me about you&mdash;are you ...</h1></p>
        <div class="span4">
          <h2>Hiring?</h2>
           <p>I'm graduating with a B.S. in Business Administration this May! I love marketing and social media - and went to Iraq and Afhganistan while in the U.S. Army. Please check out my - </p>
          <p><a class="btn" href="<%= education_path %>">Education page &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>A new internet friend?</h2>
           <p>Maybe I asked a dumb question on <%= link_to "Hacker News", "http://news.ycombinator.com/"%> or <%= link_to "Stack Overflow", "http://stackoverflow.com/questions/tagged/ruby-on-rails-3.1?sort=newest"%>. Maybe someone retweeted <%= link_to "me", "http://twitter.com/brainscraps/" %> by mistake. No matter how you found me, you can get to know me through my -</p>
          <p><a class="btn" href="<%= pers_in_path %>">Personal interests &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Family or close friend?</h2>
          <p>This is the kind of fun thing I get to do while going to <a href="<%= education_path %>">school</a>! Feel free to poke around and learn more about me. If you'd like to make fun of me, give me some feedback on the site, or catch up, please go to the - </p>
          <p><a class="btn" href="<%= contact_path %>">Contact page &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012 </p>
      </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/pers_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Welcome", root_path %></li>
              <li><%= link_to "Education", education_path %></li>
              <li><%= link_to "Experience", experience_path %></li>
              <li><%= link_to "Professional Interests", prof_in_path %></li>
              <li class="active"><%= link_to "Personal Interests", pers_in_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

    <div class="container">
      <h2>Here are some sites that I find interesting and hilarious.</h2>
        <div class="well">
          <table class="table">
            <tr>
              <td> <a href="<%= verge_url %>" alt="Link to the Verge">The Verge </a> </td>
              <td> A beautifully designed site that covers all of the latest gadgets and digital innovations</td>
            </tr>
            <tr>
              <td> <a href="<%= xkcd_url %>" alt="Link to xkcd web comic">xkcd.com </a> </td>
              <td> A web comic hand-drawn by a frighteningly intelligent programmer/rocket scientist</td>
            </tr>
            <tr>
              <td> <a href="<%= oatmeal_url %>" alt="Link to the Oatmeal">The Oatmeal</a> </td>
              <td> This comic series/blog has relevant commentary on society, the internet, and manatees</td>
            </tr>
           <tr>
              <td> <a href="<%= hn_url %>" alt="Link to Hacker News">Hacker News</a> </td>
              <td> A place for programmers, makers, and tinkerers to share their favorite bits of content from around the web</td>
            </tr>
          </table>
        </div>
              

      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012</p>
      </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/prof_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hey - it's that guy, Isaac!</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Isaac Elias</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Welcome", root_path %></li>
              <li><%= link_to "Education", education_path %></li>
              <li><%= link_to "Experience", experience_path %></li>
              <li class="active"><%= link_to "Professional Interests", prof_in_path %></li>
              <li><%= link_to "Personal Interests", pers_in_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </div>

        <div class="container">

       <h2>Here are the sites I read to stay informed when it comes to marketing and social media.</h2>
              <div class="well">
                <table class="table">
                  <tr>
                    <td> <a href="<%= pandodaily_url %>" alt="Link to Pando Daily">Pando Daily </a> </td>
                    <td> Great site to follow trends in startups, the web, and mobile commerce</td>
                  </tr>
                  <tr>
                    <td> <a href="<%= bloomberg_url %>" alt="Link to Bloomberg">Bloomberg Business </a> </td>
                    <td> Bloomberg has a robust site, with volumes of content, and very instructive videos regarding business and entrepreneurship</td>
                  </tr>
                  <tr>
                    <td> <a href="<%= tnw_url %>" alt="Link to the next web">The Next Web</a> </td>
                    <td> Reports on up-to-the-minute coverage of social media events and emerging technologies</td>
                  </tr>
                 <tr>
                    <td> <a href="http://gigaom.com" alt="Link to giga om">GigaOm</a> </td>
                    <td> Influential site started by Om Malik to cover the impact of technology and the Web on business</td>
                  </tr>
                </table>
              </div>
      <hr>

      <footer>
        <p>&copy; Isaac Elias, 2012</p>
      </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>